// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: deployPB/deploy.proto

package deployPB

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MARK: - 通知类型
type Type int32

const (
	Type_UNKNOWN         Type = 0 // 未知
	Type_CONNECT         Type = 1 // 连接成功
	Type_UPDATE_VERSION  Type = 2 // 更新版本
	Type_GET_PROVIDER    Type = 3 // 获取提供商信息
	Type_REGISTER        Type = 4 // 注册客户端
	Type_EXECUTE_BUSINES Type = 5 // 执行业务
	Type_CHALLENGE       Type = 6 // ACME HTTP-01 验证
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "UNKNOWN",
		1: "CONNECT",
		2: "UPDATE_VERSION",
		3: "GET_PROVIDER",
		4: "REGISTER",
		5: "EXECUTE_BUSINES",
		6: "CHALLENGE",
	}
	Type_value = map[string]int32{
		"UNKNOWN":         0,
		"CONNECT":         1,
		"UPDATE_VERSION":  2,
		"GET_PROVIDER":    3,
		"REGISTER":        4,
		"EXECUTE_BUSINES": 5,
		"CHALLENGE":       6,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_deployPB_deploy_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_deployPB_deploy_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_deployPB_deploy_proto_rawDescGZIP(), []int{0}
}

// MARK: - 执行业务类型
type ExecuteBusinesType int32

const (
	ExecuteBusinesType_EXECUTE_BUSINES_UNKNOWN                       ExecuteBusinesType = 0  // 未知
	ExecuteBusinesType_EXECUTE_BUSINES_ANSSL_CLI_CERT                ExecuteBusinesType = 1  // Nginx 证书部署
	ExecuteBusinesType_EXECUTE_BUSINES_UPLOAD_CERT                   ExecuteBusinesType = 2  // 上传证书
	ExecuteBusinesType_EXECUTE_BUSINES_CDN                           ExecuteBusinesType = 3  // CDN
	ExecuteBusinesType_EXECUTE_BUSINES_DCDN                          ExecuteBusinesType = 4  // DCDN
	ExecuteBusinesType_EXECUTE_BUSINES_ANSSL_CLI_APACHE_CERT         ExecuteBusinesType = 6  // Apache 证书部署
	ExecuteBusinesType_EXECUTE_BUSINES_ANSSL_CLI_RUSTFS_CERT         ExecuteBusinesType = 7  // RustFS 证书部署
	ExecuteBusinesType_EXECUTE_BUSINES_ANSSL_CLI_FEINIU_CERT         ExecuteBusinesType = 8  // 飞牛 证书部署
	ExecuteBusinesType_EXECUTE_BUSINES_ANSSL_CLI_1PANEL_CERT         ExecuteBusinesType = 9  // 1Panel 证书部署
	ExecuteBusinesType_EXECUTE_BUSINES_ANSSL_CLI_OPENVPN_AS_CERT     ExecuteBusinesType = 10 // OpenVPN-AS 证书部署
	ExecuteBusinesType_EXECUTE_BUSINES_ANSSL_CLI_UPLOAD_ONLY_CERT    ExecuteBusinesType = 11 // UploadOnly 仅上传证书
	ExecuteBusinesType_EXECUTE_BUSINES_ESA                           ExecuteBusinesType = 12 // ESA Record 证书部署
	ExecuteBusinesType_EXECUTE_BUSINES_EDGEONE                       ExecuteBusinesType = 13 // EdgeOne Host 证书部署
	ExecuteBusinesType_EXECUTE_BUSINES_COS                           ExecuteBusinesType = 14 // COS 自定义域名证书部署
	ExecuteBusinesType_EXECUTE_BUSINES_OSS_CUSTOM_DOMAIN             ExecuteBusinesType = 15 // OSS 自定义域名证书部署
	ExecuteBusinesType_EXECUTE_BUSINES_CLB                           ExecuteBusinesType = 16 // 负载均衡 CLB 证书部署
	ExecuteBusinesType_EXECUTE_BUSINES_ALB                           ExecuteBusinesType = 17 // 负载均衡 ALB 证书部署
	ExecuteBusinesType_EXECUTE_BUSINES_NLB                           ExecuteBusinesType = 18 // 负载均衡 NLB 证书部署
	ExecuteBusinesType_EXECUTE_BUSINES_ANSSL_CLI_SAFELINE_CERT       ExecuteBusinesType = 19 // 雷池 WAF 证书部署
	ExecuteBusinesType_EXECUTE_BUSINES_ANSSL_CLI_1PANEL_WEBSITE_CERT ExecuteBusinesType = 20 // 1Panel 网站证书部署
)

// Enum value maps for ExecuteBusinesType.
var (
	ExecuteBusinesType_name = map[int32]string{
		0:  "EXECUTE_BUSINES_UNKNOWN",
		1:  "EXECUTE_BUSINES_ANSSL_CLI_CERT",
		2:  "EXECUTE_BUSINES_UPLOAD_CERT",
		3:  "EXECUTE_BUSINES_CDN",
		4:  "EXECUTE_BUSINES_DCDN",
		6:  "EXECUTE_BUSINES_ANSSL_CLI_APACHE_CERT",
		7:  "EXECUTE_BUSINES_ANSSL_CLI_RUSTFS_CERT",
		8:  "EXECUTE_BUSINES_ANSSL_CLI_FEINIU_CERT",
		9:  "EXECUTE_BUSINES_ANSSL_CLI_1PANEL_CERT",
		10: "EXECUTE_BUSINES_ANSSL_CLI_OPENVPN_AS_CERT",
		11: "EXECUTE_BUSINES_ANSSL_CLI_UPLOAD_ONLY_CERT",
		12: "EXECUTE_BUSINES_ESA",
		13: "EXECUTE_BUSINES_EDGEONE",
		14: "EXECUTE_BUSINES_COS",
		15: "EXECUTE_BUSINES_OSS_CUSTOM_DOMAIN",
		16: "EXECUTE_BUSINES_CLB",
		17: "EXECUTE_BUSINES_ALB",
		18: "EXECUTE_BUSINES_NLB",
		19: "EXECUTE_BUSINES_ANSSL_CLI_SAFELINE_CERT",
		20: "EXECUTE_BUSINES_ANSSL_CLI_1PANEL_WEBSITE_CERT",
	}
	ExecuteBusinesType_value = map[string]int32{
		"EXECUTE_BUSINES_UNKNOWN":                       0,
		"EXECUTE_BUSINES_ANSSL_CLI_CERT":                1,
		"EXECUTE_BUSINES_UPLOAD_CERT":                   2,
		"EXECUTE_BUSINES_CDN":                           3,
		"EXECUTE_BUSINES_DCDN":                          4,
		"EXECUTE_BUSINES_ANSSL_CLI_APACHE_CERT":         6,
		"EXECUTE_BUSINES_ANSSL_CLI_RUSTFS_CERT":         7,
		"EXECUTE_BUSINES_ANSSL_CLI_FEINIU_CERT":         8,
		"EXECUTE_BUSINES_ANSSL_CLI_1PANEL_CERT":         9,
		"EXECUTE_BUSINES_ANSSL_CLI_OPENVPN_AS_CERT":     10,
		"EXECUTE_BUSINES_ANSSL_CLI_UPLOAD_ONLY_CERT":    11,
		"EXECUTE_BUSINES_ESA":                           12,
		"EXECUTE_BUSINES_EDGEONE":                       13,
		"EXECUTE_BUSINES_COS":                           14,
		"EXECUTE_BUSINES_OSS_CUSTOM_DOMAIN":             15,
		"EXECUTE_BUSINES_CLB":                           16,
		"EXECUTE_BUSINES_ALB":                           17,
		"EXECUTE_BUSINES_NLB":                           18,
		"EXECUTE_BUSINES_ANSSL_CLI_SAFELINE_CERT":       19,
		"EXECUTE_BUSINES_ANSSL_CLI_1PANEL_WEBSITE_CERT": 20,
	}
)

func (x ExecuteBusinesType) Enum() *ExecuteBusinesType {
	p := new(ExecuteBusinesType)
	*p = x
	return p
}

func (x ExecuteBusinesType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecuteBusinesType) Descriptor() protoreflect.EnumDescriptor {
	return file_deployPB_deploy_proto_enumTypes[1].Descriptor()
}

func (ExecuteBusinesType) Type() protoreflect.EnumType {
	return &file_deployPB_deploy_proto_enumTypes[1]
}

func (x ExecuteBusinesType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecuteBusinesType.Descriptor instead.
func (ExecuteBusinesType) EnumDescriptor() ([]byte, []int) {
	return file_deployPB_deploy_proto_rawDescGZIP(), []int{1}
}

// DeploymentResourceStatus 描述动态部署资源目录的可用状态，不携带客户端诊断信息。
type DeploymentResourceStatus int32

const (
	DeploymentResourceStatus_DEPLOYMENT_RESOURCE_STATUS_UNKNOWN           DeploymentResourceStatus = 0 // 旧客户端未上报或该业务不使用动态资源
	DeploymentResourceStatus_DEPLOYMENT_RESOURCE_STATUS_READY             DeploymentResourceStatus = 1 // 动态资源目录已成功加载
	DeploymentResourceStatus_DEPLOYMENT_RESOURCE_STATUS_EMPTY             DeploymentResourceStatus = 2 // 动态资源目录加载成功但没有可用资源
	DeploymentResourceStatus_DEPLOYMENT_RESOURCE_STATUS_NOT_CONFIGURED    DeploymentResourceStatus = 3 // deploy 客户端未配置该资源来源
	DeploymentResourceStatus_DEPLOYMENT_RESOURCE_STATUS_UNAVAILABLE       DeploymentResourceStatus = 4 // 动态资源目录暂时不可用，详细原因仅保留在客户端日志
	DeploymentResourceStatus_DEPLOYMENT_RESOURCE_STATUS_PARTIAL           DeploymentResourceStatus = 5 // 动态资源目录只完成部分扫描，已发现资源仍可使用
	DeploymentResourceStatus_DEPLOYMENT_RESOURCE_STATUS_PERMISSION_DENIED DeploymentResourceStatus = 6 // 云厂商明确拒绝访问，前端可展示该业务的静态权限指引
)

// Enum value maps for DeploymentResourceStatus.
var (
	DeploymentResourceStatus_name = map[int32]string{
		0: "DEPLOYMENT_RESOURCE_STATUS_UNKNOWN",
		1: "DEPLOYMENT_RESOURCE_STATUS_READY",
		2: "DEPLOYMENT_RESOURCE_STATUS_EMPTY",
		3: "DEPLOYMENT_RESOURCE_STATUS_NOT_CONFIGURED",
		4: "DEPLOYMENT_RESOURCE_STATUS_UNAVAILABLE",
		5: "DEPLOYMENT_RESOURCE_STATUS_PARTIAL",
		6: "DEPLOYMENT_RESOURCE_STATUS_PERMISSION_DENIED",
	}
	DeploymentResourceStatus_value = map[string]int32{
		"DEPLOYMENT_RESOURCE_STATUS_UNKNOWN":           0,
		"DEPLOYMENT_RESOURCE_STATUS_READY":             1,
		"DEPLOYMENT_RESOURCE_STATUS_EMPTY":             2,
		"DEPLOYMENT_RESOURCE_STATUS_NOT_CONFIGURED":    3,
		"DEPLOYMENT_RESOURCE_STATUS_UNAVAILABLE":       4,
		"DEPLOYMENT_RESOURCE_STATUS_PARTIAL":           5,
		"DEPLOYMENT_RESOURCE_STATUS_PERMISSION_DENIED": 6,
	}
)

func (x DeploymentResourceStatus) Enum() *DeploymentResourceStatus {
	p := new(DeploymentResourceStatus)
	*p = x
	return p
}

func (x DeploymentResourceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeploymentResourceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_deployPB_deploy_proto_enumTypes[2].Descriptor()
}

func (DeploymentResourceStatus) Type() protoreflect.EnumType {
	return &file_deployPB_deploy_proto_enumTypes[2]
}

func (x DeploymentResourceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeploymentResourceStatus.Descriptor instead.
func (DeploymentResourceStatus) EnumDescriptor() ([]byte, []int) {
	return file_deployPB_deploy_proto_rawDescGZIP(), []int{2}
}

// DeploymentResourceAvailability 描述单个动态部署资源当前是否可以执行证书部署。
type DeploymentResourceAvailability int32

const (
	DeploymentResourceAvailability_DEPLOYMENT_RESOURCE_AVAILABILITY_UNKNOWN     DeploymentResourceAvailability = 0 // 旧客户端未上报资源可用性
	DeploymentResourceAvailability_DEPLOYMENT_RESOURCE_AVAILABILITY_READY       DeploymentResourceAvailability = 1 // 资源状态正常，可以测试和部署
	DeploymentResourceAvailability_DEPLOYMENT_RESOURCE_AVAILABILITY_STOPPED     DeploymentResourceAvailability = 2 // 资源已停止运行
	DeploymentResourceAvailability_DEPLOYMENT_RESOURCE_AVAILABILITY_DISABLED    DeploymentResourceAvailability = 3 // 资源或 HTTPS 能力已禁用
	DeploymentResourceAvailability_DEPLOYMENT_RESOURCE_AVAILABILITY_LOCKED      DeploymentResourceAvailability = 4 // 资源因冻结、锁定等状态不可修改
	DeploymentResourceAvailability_DEPLOYMENT_RESOURCE_AVAILABILITY_UNSUPPORTED DeploymentResourceAvailability = 5 // 资源形态暂不支持精确部署
)

// Enum value maps for DeploymentResourceAvailability.
var (
	DeploymentResourceAvailability_name = map[int32]string{
		0: "DEPLOYMENT_RESOURCE_AVAILABILITY_UNKNOWN",
		1: "DEPLOYMENT_RESOURCE_AVAILABILITY_READY",
		2: "DEPLOYMENT_RESOURCE_AVAILABILITY_STOPPED",
		3: "DEPLOYMENT_RESOURCE_AVAILABILITY_DISABLED",
		4: "DEPLOYMENT_RESOURCE_AVAILABILITY_LOCKED",
		5: "DEPLOYMENT_RESOURCE_AVAILABILITY_UNSUPPORTED",
	}
	DeploymentResourceAvailability_value = map[string]int32{
		"DEPLOYMENT_RESOURCE_AVAILABILITY_UNKNOWN":     0,
		"DEPLOYMENT_RESOURCE_AVAILABILITY_READY":       1,
		"DEPLOYMENT_RESOURCE_AVAILABILITY_STOPPED":     2,
		"DEPLOYMENT_RESOURCE_AVAILABILITY_DISABLED":    3,
		"DEPLOYMENT_RESOURCE_AVAILABILITY_LOCKED":      4,
		"DEPLOYMENT_RESOURCE_AVAILABILITY_UNSUPPORTED": 5,
	}
)

func (x DeploymentResourceAvailability) Enum() *DeploymentResourceAvailability {
	p := new(DeploymentResourceAvailability)
	*p = x
	return p
}

func (x DeploymentResourceAvailability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeploymentResourceAvailability) Descriptor() protoreflect.EnumDescriptor {
	return file_deployPB_deploy_proto_enumTypes[3].Descriptor()
}

func (DeploymentResourceAvailability) Type() protoreflect.EnumType {
	return &file_deployPB_deploy_proto_enumTypes[3]
}

func (x DeploymentResourceAvailability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeploymentResourceAvailability.Descriptor instead.
func (DeploymentResourceAvailability) EnumDescriptor() ([]byte, []int) {
	return file_deployPB_deploy_proto_rawDescGZIP(), []int{3}
}

type ChallengeRequest_Action int32

const (
	ChallengeRequest_CHALLENGE_ACTION_UNKNOWN ChallengeRequest_Action = 0 // 未知操作
	ChallengeRequest_CHALLENGE_ACTION_SET     ChallengeRequest_Action = 1 // 设置 challenge
	ChallengeRequest_CHALLENGE_ACTION_DELETE  ChallengeRequest_Action = 2 // 删除 challenge
)

// Enum value maps for ChallengeRequest_Action.
var (
	ChallengeRequest_Action_name = map[int32]string{
		0: "CHALLENGE_ACTION_UNKNOWN",
		1: "CHALLENGE_ACTION_SET",
		2: "CHALLENGE_ACTION_DELETE",
	}
	ChallengeRequest_Action_value = map[string]int32{
		"CHALLENGE_ACTION_UNKNOWN": 0,
		"CHALLENGE_ACTION_SET":     1,
		"CHALLENGE_ACTION_DELETE":  2,
	}
)

func (x ChallengeRequest_Action) Enum() *ChallengeRequest_Action {
	p := new(ChallengeRequest_Action)
	*p = x
	return p
}

func (x ChallengeRequest_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChallengeRequest_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_deployPB_deploy_proto_enumTypes[4].Descriptor()
}

func (ChallengeRequest_Action) Type() protoreflect.EnumType {
	return &file_deployPB_deploy_proto_enumTypes[4]
}

func (x ChallengeRequest_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChallengeRequest_Action.Descriptor instead.
func (ChallengeRequest_Action) EnumDescriptor() ([]byte, []int) {
	return file_deployPB_deploy_proto_rawDescGZIP(), []int{5, 0}
}

type ChallengeResponse_Result int32

const (
	ChallengeResponse_CHALLENGE_RESULT_UNKNOWN       ChallengeResponse_Result = 0 // 未知结果
	ChallengeResponse_CHALLENGE_RESULT_SUCCESS       ChallengeResponse_Result = 1 // 执行成功
	ChallengeResponse_CHALLENGE_RESULT_FAILED        ChallengeResponse_Result = 2 // 执行失败
	ChallengeResponse_CHALLENGE_RESULT_NOT_SUPPORTED ChallengeResponse_Result = 3 // 客户端不支持
)

// Enum value maps for ChallengeResponse_Result.
var (
	ChallengeResponse_Result_name = map[int32]string{
		0: "CHALLENGE_RESULT_UNKNOWN",
		1: "CHALLENGE_RESULT_SUCCESS",
		2: "CHALLENGE_RESULT_FAILED",
		3: "CHALLENGE_RESULT_NOT_SUPPORTED",
	}
	ChallengeResponse_Result_value = map[string]int32{
		"CHALLENGE_RESULT_UNKNOWN":       0,
		"CHALLENGE_RESULT_SUCCESS":       1,
		"CHALLENGE_RESULT_FAILED":        2,
		"CHALLENGE_RESULT_NOT_SUPPORTED": 3,
	}
)

func (x ChallengeResponse_Result) Enum() *ChallengeResponse_Result {
	p := new(ChallengeResponse_Result)
	*p = x
	return p
}

func (x ChallengeResponse_Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChallengeResponse_Result) Descriptor() protoreflect.EnumDescriptor {
	return file_deployPB_deploy_proto_enumTypes[5].Descriptor()
}

func (ChallengeResponse_Result) Type() protoreflect.EnumType {
	return &file_deployPB_deploy_proto_enumTypes[5]
}

func (x ChallengeResponse_Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChallengeResponse_Result.Descriptor instead.
func (ChallengeResponse_Result) EnumDescriptor() ([]byte, []int) {
	return file_deployPB_deploy_proto_rawDescGZIP(), []int{6, 0}
}

// 请求结果
type ExecuteBusinesRequest_RequestResult int32

const (
	ExecuteBusinesRequest_REQUEST_RESULT_UNKNOWN       ExecuteBusinesRequest_RequestResult = 0 // 未知
	ExecuteBusinesRequest_REQUEST_RESULT_SUCCESS       ExecuteBusinesRequest_RequestResult = 1 // 成功
	ExecuteBusinesRequest_REQUEST_RESULT_FAILED        ExecuteBusinesRequest_RequestResult = 2 // 失败
	ExecuteBusinesRequest_REQUEST_RESULT_NOT_SUPPORTED ExecuteBusinesRequest_RequestResult = 3 // 不支持
)

// Enum value maps for ExecuteBusinesRequest_RequestResult.
var (
	ExecuteBusinesRequest_RequestResult_name = map[int32]string{
		0: "REQUEST_RESULT_UNKNOWN",
		1: "REQUEST_RESULT_SUCCESS",
		2: "REQUEST_RESULT_FAILED",
		3: "REQUEST_RESULT_NOT_SUPPORTED",
	}
	ExecuteBusinesRequest_RequestResult_value = map[string]int32{
		"REQUEST_RESULT_UNKNOWN":       0,
		"REQUEST_RESULT_SUCCESS":       1,
		"REQUEST_RESULT_FAILED":        2,
		"REQUEST_RESULT_NOT_SUPPORTED": 3,
	}
)

func (x ExecuteBusinesRequest_RequestResult) Enum() *ExecuteBusinesRequest_RequestResult {
	p := new(ExecuteBusinesRequest_RequestResult)
	*p = x
	return p
}

func (x ExecuteBusinesRequest_RequestResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecuteBusinesRequest_RequestResult) Descriptor() protoreflect.EnumDescriptor {
	return file_deployPB_deploy_proto_enumTypes[6].Descriptor()
}

func (ExecuteBusinesRequest_RequestResult) Type() protoreflect.EnumType {
	return &file_deployPB_deploy_proto_enumTypes[6]
}

func (x ExecuteBusinesRequest_RequestResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecuteBusinesRequest_RequestResult.Descriptor instead.
func (ExecuteBusinesRequest_RequestResult) EnumDescriptor() ([]byte, []int) {
	return file_deployPB_deploy_proto_rawDescGZIP(), []int{12, 0}
}

// MARK: - 通知
type NotifyRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	AccessKey string                 `protobuf:"bytes,1,opt,name=accessKey,proto3" json:"accessKey,omitempty"` // 令牌
	ClientId  string                 `protobuf:"bytes,2,opt,name=clientId,proto3" json:"clientId,omitempty"`   // 客户端ID
	RequestId string                 `protobuf:"bytes,3,opt,name=requestId,proto3" json:"requestId,omitempty"` // 请求ID（用于请求-响应匹配）
	Version   string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`     // 客户端版本
	// Types that are valid to be assigned to Data:
	//
	//	*NotifyRequest_GetProviderResponse
	//	*NotifyRequest_RegisterResponse
	//	*NotifyRequest_ConnectRequest
	//	*NotifyRequest_ExecuteBusinesRequest
	//	*NotifyRequest_ChallengeResponse
	Data          isNotifyRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyRequest) Reset() {
	*x = NotifyRequest{}
	mi := &file_deployPB_deploy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyRequest) ProtoMessage() {}

func (x *NotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deployPB_deploy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyRequest.ProtoReflect.Descriptor instead.
func (*NotifyRequest) Descriptor() ([]byte, []int) {
	return file_deployPB_deploy_proto_rawDescGZIP(), []int{0}
}

func (x *NotifyRequest) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *NotifyRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *NotifyRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *NotifyRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *NotifyRequest) GetData() isNotifyRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *NotifyRequest) GetGetProviderResponse() *GetProviderResponse {
	if x != nil {
		if x, ok := x.Data.(*NotifyRequest_GetProviderResponse); ok {
			return x.GetProviderResponse
		}
	}
	return nil
}

func (x *NotifyRequest) GetRegisterResponse() *RegisterResponse {
	if x != nil {
		if x, ok := x.Data.(*NotifyRequest_RegisterResponse); ok {
			return x.RegisterResponse
		}
	}
	return nil
}

func (x *NotifyRequest) GetConnectRequest() *ConnectRequest {
	if x != nil {
		if x, ok := x.Data.(*NotifyRequest_ConnectRequest); ok {
			return x.ConnectRequest
		}
	}
	return nil
}

func (x *NotifyRequest) GetExecuteBusinesRequest() *ExecuteBusinesRequest {
	if x != nil {
		if x, ok := x.Data.(*NotifyRequest_ExecuteBusinesRequest); ok {
			return x.ExecuteBusinesRequest
		}
	}
	return nil
}

func (x *NotifyRequest) GetChallengeResponse() *ChallengeResponse {
	if x != nil {
		if x, ok := x.Data.(*NotifyRequest_ChallengeResponse); ok {
			return x.ChallengeResponse
		}
	}
	return nil
}

type isNotifyRequest_Data interface {
	isNotifyRequest_Data()
}

type NotifyRequest_GetProviderResponse struct {
	GetProviderResponse *GetProviderResponse `protobuf:"bytes,10,opt,name=getProviderResponse,proto3,oneof"`
}

type NotifyRequest_RegisterResponse struct {
	RegisterResponse *RegisterResponse `protobuf:"bytes,11,opt,name=registerResponse,proto3,oneof"`
}

type NotifyRequest_ConnectRequest struct {
	ConnectRequest *ConnectRequest `protobuf:"bytes,12,opt,name=connectRequest,proto3,oneof"`
}

type NotifyRequest_ExecuteBusinesRequest struct {
	ExecuteBusinesRequest *ExecuteBusinesRequest `protobuf:"bytes,13,opt,name=executeBusinesRequest,proto3,oneof"`
}

type NotifyRequest_ChallengeResponse struct {
	ChallengeResponse *ChallengeResponse `protobuf:"bytes,14,opt,name=challengeResponse,proto3,oneof"`
}

func (*NotifyRequest_GetProviderResponse) isNotifyRequest_Data() {}

func (*NotifyRequest_RegisterResponse) isNotifyRequest_Data() {}

func (*NotifyRequest_ConnectRequest) isNotifyRequest_Data() {}

func (*NotifyRequest_ExecuteBusinesRequest) isNotifyRequest_Data() {}

func (*NotifyRequest_ChallengeResponse) isNotifyRequest_Data() {}

type NotifyResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Type      Type                   `protobuf:"varint,1,opt,name=type,proto3,enum=deployPB.Type" json:"type,omitempty"` // 类型
	ClientId  string                 `protobuf:"bytes,2,opt,name=clientId,proto3" json:"clientId,omitempty"`             // 客户端ID
	RequestId string                 `protobuf:"bytes,3,opt,name=requestId,proto3" json:"requestId,omitempty"`           // 请求ID（用于请求-响应匹配）
	// Types that are valid to be assigned to Data:
	//
	//	*NotifyResponse_GetProviderResponse
	//	*NotifyResponse_RegisterRequest
	//	*NotifyResponse_ConnectRequest
	//	*NotifyResponse_ExecuteBusinesResponse
	//	*NotifyResponse_ChallengeRequest
	//	*NotifyResponse_GetProviderRequest
	Data          isNotifyResponse_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyResponse) Reset() {
	*x = NotifyResponse{}
	mi := &file_deployPB_deploy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyResponse) ProtoMessage() {}

func (x *NotifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deployPB_deploy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyResponse.ProtoReflect.Descriptor instead.
func (*NotifyResponse) Descriptor() ([]byte, []int) {
	return file_deployPB_deploy_proto_rawDescGZIP(), []int{1}
}

func (x *NotifyResponse) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_UNKNOWN
}

func (x *NotifyResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *NotifyResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *NotifyResponse) GetData() isNotifyResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *NotifyResponse) GetGetProviderResponse() *GetProviderResponse {
	if x != nil {
		if x, ok := x.Data.(*NotifyResponse_GetProviderResponse); ok {
			return x.GetProviderResponse
		}
	}
	return nil
}

func (x *NotifyResponse) GetRegisterRequest() *RegisterRequest {
	if x != nil {
		if x, ok := x.Data.(*NotifyResponse_RegisterRequest); ok {
			return x.RegisterRequest
		}
	}
	return nil
}

func (x *NotifyResponse) GetConnectRequest() *ConnectRequest {
	if x != nil {
		if x, ok := x.Data.(*NotifyResponse_ConnectRequest); ok {
			return x.ConnectRequest
		}
	}
	return nil
}

func (x *NotifyResponse) GetExecuteBusinesResponse() *ExecuteBusinesResponse {
	if x != nil {
		if x, ok := x.Data.(*NotifyResponse_ExecuteBusinesResponse); ok {
			return x.ExecuteBusinesResponse
		}
	}
	return nil
}

func (x *NotifyResponse) GetChallengeRequest() *ChallengeRequest {
	if x != nil {
		if x, ok := x.Data.(*NotifyResponse_ChallengeRequest); ok {
			return x.ChallengeRequest
		}
	}
	return nil
}

func (x *NotifyResponse) GetGetProviderRequest() *GetProviderRequest {
	if x != nil {
		if x, ok := x.Data.(*NotifyResponse_GetProviderRequest); ok {
			return x.GetProviderRequest
		}
	}
	return nil
}

type isNotifyResponse_Data interface {
	isNotifyResponse_Data()
}

type NotifyResponse_GetProviderResponse struct {
	GetProviderResponse *GetProviderResponse `protobuf:"bytes,5,opt,name=getProviderResponse,proto3,oneof"`
}

type NotifyResponse_RegisterRequest struct {
	RegisterRequest *RegisterRequest `protobuf:"bytes,6,opt,name=registerRequest,proto3,oneof"`
}

type NotifyResponse_ConnectRequest struct {
	ConnectRequest *ConnectRequest `protobuf:"bytes,7,opt,name=connectRequest,proto3,oneof"`
}

type NotifyResponse_ExecuteBusinesResponse struct {
	ExecuteBusinesResponse *ExecuteBusinesResponse `protobuf:"bytes,8,opt,name=executeBusinesResponse,proto3,oneof"`
}

type NotifyResponse_ChallengeRequest struct {
	ChallengeRequest *ChallengeRequest `protobuf:"bytes,9,opt,name=challengeRequest,proto3,oneof"`
}

type NotifyResponse_GetProviderRequest struct {
	GetProviderRequest *GetProviderRequest `protobuf:"bytes,10,opt,name=getProviderRequest,proto3,oneof"`
}

func (*NotifyResponse_GetProviderResponse) isNotifyResponse_Data() {}

func (*NotifyResponse_RegisterRequest) isNotifyResponse_Data() {}

func (*NotifyResponse_ConnectRequest) isNotifyResponse_Data() {}

func (*NotifyResponse_ExecuteBusinesResponse) isNotifyResponse_Data() {}

func (*NotifyResponse_ChallengeRequest) isNotifyResponse_Data() {}

func (*NotifyResponse_GetProviderRequest) isNotifyResponse_Data() {}

// MARK: - Connect: 连接
type ConnectRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Provider           string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`                                                                                   // 提供商
	Success            bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`                                                                                    // 是否成功
	ExecuteBusinesType ExecuteBusinesType     `protobuf:"varint,3,opt,name=execute_busines_type,json=executeBusinesType,proto3,enum=deployPB.ExecuteBusinesType" json:"execute_busines_type,omitempty"` // 需要测试的具体部署业务
	TargetRef          string                 `protobuf:"bytes,5,opt,name=target_ref,json=targetRef,proto3" json:"target_ref,omitempty"`                                                                // 资源型业务需要测试的客户端不透明资源引用
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_deployPB_deploy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deployPB_deploy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_deployPB_deploy_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ConnectRequest) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConnectRequest) GetExecuteBusinesType() ExecuteBusinesType {
	if x != nil {
		return x.ExecuteBusinesType
	}
	return ExecuteBusinesType_EXECUTE_BUSINES_UNKNOWN
}

func (x *ConnectRequest) GetTargetRef() string {
	if x != nil {
		return x.TargetRef
	}
	return ""
}

// MARK: - 证书更新
type CertUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertUpdateRequest) Reset() {
	*x = CertUpdateRequest{}
	mi := &file_deployPB_deploy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertUpdateRequest) ProtoMessage() {}

func (x *CertUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deployPB_deploy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertUpdateRequest.ProtoReflect.Descriptor instead.
func (*CertUpdateRequest) Descriptor() ([]byte, []int) {
	return file_deployPB_deploy_proto_rawDescGZIP(), []int{3}
}

type CertUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"` // 域名
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`       // 证书下载URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertUpdateResponse) Reset() {
	*x = CertUpdateResponse{}
	mi := &file_deployPB_deploy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertUpdateResponse) ProtoMessage() {}

func (x *CertUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deployPB_deploy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertUpdateResponse.ProtoReflect.Descriptor instead.
func (*CertUpdateResponse) Descriptor() ([]byte, []int) {
	return file_deployPB_deploy_proto_rawDescGZIP(), []int{4}
}

func (x *CertUpdateResponse) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *CertUpdateResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// MARK: - HTTP-01 challenge
// ChallengeRequest 要求 deploy 客户端设置或删除一条精确的 HTTP-01 challenge。
type ChallengeRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	OperationId   int64                   `protobuf:"varint,1,opt,name=operationId,proto3" json:"operationId,omitempty"`                             // 证书操作 ID
	CertId        int32                   `protobuf:"varint,2,opt,name=certId,proto3" json:"certId,omitempty"`                                       // 证书 ID
	Domain        string                  `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`                                        // 验证域名
	Token         string                  `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`                                          // ACME challenge token
	KeyAuth       string                  `protobuf:"bytes,5,opt,name=keyAuth,proto3" json:"keyAuth,omitempty"`                                      // HTTP 端点应返回的 key authorization
	Action        ChallengeRequest_Action `protobuf:"varint,6,opt,name=action,proto3,enum=deployPB.ChallengeRequest_Action" json:"action,omitempty"` // 客户端需要执行的动作
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChallengeRequest) Reset() {
	*x = ChallengeRequest{}
	mi := &file_deployPB_deploy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeRequest) ProtoMessage() {}

func (x *ChallengeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deployPB_deploy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeRequest.ProtoReflect.Descriptor instead.
func (*ChallengeRequest) Descriptor() ([]byte, []int) {
	return file_deployPB_deploy_proto_rawDescGZIP(), []int{5}
}

func (x *ChallengeRequest) GetOperationId() int64 {
	if x != nil {
		return x.OperationId
	}
	return 0
}

func (x *ChallengeRequest) GetCertId() int32 {
	if x != nil {
		return x.CertId
	}
	return 0
}

func (x *ChallengeRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ChallengeRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ChallengeRequest) GetKeyAuth() string {
	if x != nil {
		return x.KeyAuth
	}
	return ""
}

func (x *ChallengeRequest) GetAction() ChallengeRequest_Action {
	if x != nil {
		return x.Action
	}
	return ChallengeRequest_CHALLENGE_ACTION_UNKNOWN
}

// ChallengeResponse 返回 deploy 客户端执行 challenge 请求的明确结果。
type ChallengeResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	OperationId   int64                    `protobuf:"varint,1,opt,name=operationId,proto3" json:"operationId,omitempty"`                              // 证书操作 ID
	CertId        int32                    `protobuf:"varint,2,opt,name=certId,proto3" json:"certId,omitempty"`                                        // 证书 ID
	Domain        string                   `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`                                         // 验证域名
	Token         string                   `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`                                           // ACME challenge token
	Result        ChallengeResponse_Result `protobuf:"varint,5,opt,name=result,proto3,enum=deployPB.ChallengeResponse_Result" json:"result,omitempty"` // 客户端执行结果
	Message       string                   `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`                                       // 失败原因或成功说明
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChallengeResponse) Reset() {
	*x = ChallengeResponse{}
	mi := &file_deployPB_deploy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeResponse) ProtoMessage() {}

func (x *ChallengeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deployPB_deploy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeResponse.ProtoReflect.Descriptor instead.
func (*ChallengeResponse) Descriptor() ([]byte, []int) {
	return file_deployPB_deploy_proto_rawDescGZIP(), []int{6}
}

func (x *ChallengeResponse) GetOperationId() int64 {
	if x != nil {
		return x.OperationId
	}
	return 0
}

func (x *ChallengeResponse) GetCertId() int32 {
	if x != nil {
		return x.CertId
	}
	return 0
}

func (x *ChallengeResponse) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ChallengeResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ChallengeResponse) GetResult() ChallengeResponse_Result {
	if x != nil {
		return x.Result
	}
	return ChallengeResponse_CHALLENGE_RESULT_UNKNOWN
}

func (x *ChallengeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// MARK: - 获取提供商信息
type GetProviderRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Provider           string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`                                                                                   // 为空时返回全部已配置 provider 的轻量能力
	ExecuteBusinesType ExecuteBusinesType     `protobuf:"varint,2,opt,name=execute_busines_type,json=executeBusinesType,proto3,enum=deployPB.ExecuteBusinesType" json:"execute_busines_type,omitempty"` // include_resources=true 时只扫描这一项业务
	IncludeResources   bool                   `protobuf:"varint,3,opt,name=include_resources,json=includeResources,proto3" json:"include_resources,omitempty"`                                          // 是否实时读取指定业务的资源目录
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetProviderRequest) Reset() {
	*x = GetProviderRequest{}
	mi := &file_deployPB_deploy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderRequest) ProtoMessage() {}

func (x *GetProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deployPB_deploy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderRequest.ProtoReflect.Descriptor instead.
func (*GetProviderRequest) Descriptor() ([]byte, []int) {
	return file_deployPB_deploy_proto_rawDescGZIP(), []int{7}
}

func (x *GetProviderRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *GetProviderRequest) GetExecuteBusinesType() ExecuteBusinesType {
	if x != nil {
		return x.ExecuteBusinesType
	}
	return ExecuteBusinesType_EXECUTE_BUSINES_UNKNOWN
}

func (x *GetProviderRequest) GetIncludeResources() bool {
	if x != nil {
		return x.IncludeResources
	}
	return false
}

// DeployResource 是某项明确部署业务下可选择的脱敏资源。
type DeployResource struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	TargetRef     string                         `protobuf:"bytes,1,opt,name=target_ref,json=targetRef,proto3" json:"target_ref,omitempty"`                                     // 客户端根据本地资源定位参数生成的不透明引用
	Label         string                         `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`                                                              // 供控制台展示的资源名称
	Domain        string                         `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`                                                            // 资源绑定的精确域名
	Domains       []string                       `protobuf:"bytes,4,rep,name=domains,proto3" json:"domains,omitempty"`                                                          // 资源绑定的全部规范化域名
	Protocol      string                         `protobuf:"bytes,5,opt,name=protocol,proto3" json:"protocol,omitempty"`                                                        // 资源当前协议，仅动态面板网站资源上报 HTTP 或 HTTPS
	Status        string                         `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`                                                            // 资源当前运行状态，仅动态面板网站资源上报 Running 或 Stopped
	Group         string                         `protobuf:"bytes,7,opt,name=group,proto3" json:"group,omitempty"`                                                              // 资源所属站点、Bucket 或负载均衡实例的脱敏展示名称
	Region        string                         `protobuf:"bytes,8,opt,name=region,proto3" json:"region,omitempty"`                                                            // 资源所在地域的公开名称或代码
	Port          uint32                         `protobuf:"varint,9,opt,name=port,proto3" json:"port,omitempty"`                                                               // 负载均衡监听端口，非监听器资源为 0
	Availability  DeploymentResourceAvailability `protobuf:"varint,10,opt,name=availability,proto3,enum=deployPB.DeploymentResourceAvailability" json:"availability,omitempty"` // 资源当前是否允许选择、测试和部署
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployResource) Reset() {
	*x = DeployResource{}
	mi := &file_deployPB_deploy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployResource) ProtoMessage() {}

func (x *DeployResource) ProtoReflect() protoreflect.Message {
	mi := &file_deployPB_deploy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployResource.ProtoReflect.Descriptor instead.
func (*DeployResource) Descriptor() ([]byte, []int) {
	return file_deployPB_deploy_proto_rawDescGZIP(), []int{8}
}

func (x *DeployResource) GetTargetRef() string {
	if x != nil {
		return x.TargetRef
	}
	return ""
}

func (x *DeployResource) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *DeployResource) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *DeployResource) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

func (x *DeployResource) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *DeployResource) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeployResource) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *DeployResource) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *DeployResource) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *DeployResource) GetAvailability() DeploymentResourceAvailability {
	if x != nil {
		return x.Availability
	}
	return DeploymentResourceAvailability_DEPLOYMENT_RESOURCE_AVAILABILITY_UNKNOWN
}

type GetProviderResponse struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Providers     []*GetProviderResponse_Provider `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderResponse) Reset() {
	*x = GetProviderResponse{}
	mi := &file_deployPB_deploy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderResponse) ProtoMessage() {}

func (x *GetProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deployPB_deploy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderResponse.ProtoReflect.Descriptor instead.
func (*GetProviderResponse) Descriptor() ([]byte, []int) {
	return file_deployPB_deploy_proto_rawDescGZIP(), []int{9}
}

func (x *GetProviderResponse) GetProviders() []*GetProviderResponse_Provider {
	if x != nil {
		return x.Providers
	}
	return nil
}

// MARK: - 注册客户端
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_deployPB_deploy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deployPB_deploy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_deployPB_deploy_proto_rawDescGZIP(), []int{10}
}

type RegisterResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	SystemInfo    *RegisterResponse_SystemInfo `protobuf:"bytes,1,opt,name=systemInfo,proto3" json:"systemInfo,omitempty"` // 系统信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_deployPB_deploy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deployPB_deploy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_deployPB_deploy_proto_rawDescGZIP(), []int{11}
}

func (x *RegisterResponse) GetSystemInfo() *RegisterResponse_SystemInfo {
	if x != nil {
		return x.SystemInfo
	}
	return nil
}

// MARK: - 执行业务
type ExecuteBusinesRequest struct {
	state             protoimpl.MessageState              `protogen:"open.v1"`
	RequestResult     ExecuteBusinesRequest_RequestResult `protobuf:"varint,1,opt,name=requestResult,proto3,enum=deployPB.ExecuteBusinesRequest_RequestResult" json:"requestResult,omitempty"` // 请求结果
	Message           string                              `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                                                // 失败原因或成功说明
	Retryable         *bool                               `protobuf:"varint,3,opt,name=retryable,proto3,oneof" json:"retryable,omitempty"`                                                     // 是否建议后端重试；未设置表示旧客户端未分类
	ProviderRequestId string                              `protobuf:"bytes,4,opt,name=provider_request_id,json=providerRequestId,proto3" json:"provider_request_id,omitempty"`                 // 云厂商请求 ID，便于排查 API 调用
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExecuteBusinesRequest) Reset() {
	*x = ExecuteBusinesRequest{}
	mi := &file_deployPB_deploy_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteBusinesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteBusinesRequest) ProtoMessage() {}

func (x *ExecuteBusinesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deployPB_deploy_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteBusinesRequest.ProtoReflect.Descriptor instead.
func (*ExecuteBusinesRequest) Descriptor() ([]byte, []int) {
	return file_deployPB_deploy_proto_rawDescGZIP(), []int{12}
}

func (x *ExecuteBusinesRequest) GetRequestResult() ExecuteBusinesRequest_RequestResult {
	if x != nil {
		return x.RequestResult
	}
	return ExecuteBusinesRequest_REQUEST_RESULT_UNKNOWN
}

func (x *ExecuteBusinesRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExecuteBusinesRequest) GetRetryable() bool {
	if x != nil && x.Retryable != nil {
		return *x.Retryable
	}
	return false
}

func (x *ExecuteBusinesRequest) GetProviderRequestId() string {
	if x != nil {
		return x.ProviderRequestId
	}
	return ""
}

type ExecuteBusinesResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Provider           string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`                                                       // 提供商
	ExecuteBusinesType ExecuteBusinesType     `protobuf:"varint,2,opt,name=executeBusinesType,proto3,enum=deployPB.ExecuteBusinesType" json:"executeBusinesType,omitempty"` // 执行业务类型
	Domain             string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`                                                           // 域名
	Url                string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`                                                                 // 证书下载URL
	Cert               string                 `protobuf:"bytes,5,opt,name=cert,proto3" json:"cert,omitempty"`                                                               // 证书
	Key                string                 `protobuf:"bytes,6,opt,name=key,proto3" json:"key,omitempty"`                                                                 // 私钥
	ChallengeToken     string                 `protobuf:"bytes,7,opt,name=challengeToken,proto3" json:"challengeToken,omitempty"`                                           // ACME challenge token
	ChallengeResponse  string                 `protobuf:"bytes,8,opt,name=challengeResponse,proto3" json:"challengeResponse,omitempty"`                                     // ACME challenge response
	TargetRef          string                 `protobuf:"bytes,9,opt,name=target_ref,json=targetRef,proto3" json:"target_ref,omitempty"`                                    // 客户端本地配置中的精确部署资源引用
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ExecuteBusinesResponse) Reset() {
	*x = ExecuteBusinesResponse{}
	mi := &file_deployPB_deploy_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteBusinesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteBusinesResponse) ProtoMessage() {}

func (x *ExecuteBusinesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deployPB_deploy_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteBusinesResponse.ProtoReflect.Descriptor instead.
func (*ExecuteBusinesResponse) Descriptor() ([]byte, []int) {
	return file_deployPB_deploy_proto_rawDescGZIP(), []int{13}
}

func (x *ExecuteBusinesResponse) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ExecuteBusinesResponse) GetExecuteBusinesType() ExecuteBusinesType {
	if x != nil {
		return x.ExecuteBusinesType
	}
	return ExecuteBusinesType_EXECUTE_BUSINES_UNKNOWN
}

func (x *ExecuteBusinesResponse) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ExecuteBusinesResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ExecuteBusinesResponse) GetCert() string {
	if x != nil {
		return x.Cert
	}
	return ""
}

func (x *ExecuteBusinesResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ExecuteBusinesResponse) GetChallengeToken() string {
	if x != nil {
		return x.ChallengeToken
	}
	return ""
}

func (x *ExecuteBusinesResponse) GetChallengeResponse() string {
	if x != nil {
		return x.ChallengeResponse
	}
	return ""
}

func (x *ExecuteBusinesResponse) GetTargetRef() string {
	if x != nil {
		return x.TargetRef
	}
	return ""
}

type GetProviderResponse_Provider struct {
	state         protoimpl.MessageState                   `protogen:"open.v1"`
	Name          string                                   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`             // 提供商名称
	Remark        string                                   `protobuf:"bytes,2,opt,name=remark,proto3" json:"remark,omitempty"`         // 备注
	Businesses    []*GetProviderResponse_Provider_Business `protobuf:"bytes,3,rep,name=businesses,proto3" json:"businesses,omitempty"` // 按明确部署业务分组的资源目录
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderResponse_Provider) Reset() {
	*x = GetProviderResponse_Provider{}
	mi := &file_deployPB_deploy_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderResponse_Provider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderResponse_Provider) ProtoMessage() {}

func (x *GetProviderResponse_Provider) ProtoReflect() protoreflect.Message {
	mi := &file_deployPB_deploy_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderResponse_Provider.ProtoReflect.Descriptor instead.
func (*GetProviderResponse_Provider) Descriptor() ([]byte, []int) {
	return file_deployPB_deploy_proto_rawDescGZIP(), []int{9, 0}
}

func (x *GetProviderResponse_Provider) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetProviderResponse_Provider) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *GetProviderResponse_Provider) GetBusinesses() []*GetProviderResponse_Provider_Business {
	if x != nil {
		return x.Businesses
	}
	return nil
}

type GetProviderResponse_Provider_Business struct {
	state              protoimpl.MessageState   `protogen:"open.v1"`
	ExecuteBusinesType ExecuteBusinesType       `protobuf:"varint,1,opt,name=execute_busines_type,json=executeBusinesType,proto3,enum=deployPB.ExecuteBusinesType" json:"execute_busines_type,omitempty"` // CDN、DCDN、ESA、OSS、EdgeOne、COS 或 CLB 等明确业务
	Resources          []*DeployResource        `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty"`                                                                                 // 当前业务下可部署的脱敏资源目录
	ResourceStatus     DeploymentResourceStatus `protobuf:"varint,3,opt,name=resource_status,json=resourceStatus,proto3,enum=deployPB.DeploymentResourceStatus" json:"resource_status,omitempty"`         // 动态资源目录状态，不包含客户端错误详情
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetProviderResponse_Provider_Business) Reset() {
	*x = GetProviderResponse_Provider_Business{}
	mi := &file_deployPB_deploy_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderResponse_Provider_Business) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderResponse_Provider_Business) ProtoMessage() {}

func (x *GetProviderResponse_Provider_Business) ProtoReflect() protoreflect.Message {
	mi := &file_deployPB_deploy_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderResponse_Provider_Business.ProtoReflect.Descriptor instead.
func (*GetProviderResponse_Provider_Business) Descriptor() ([]byte, []int) {
	return file_deployPB_deploy_proto_rawDescGZIP(), []int{9, 0, 0}
}

func (x *GetProviderResponse_Provider_Business) GetExecuteBusinesType() ExecuteBusinesType {
	if x != nil {
		return x.ExecuteBusinesType
	}
	return ExecuteBusinesType_EXECUTE_BUSINES_UNKNOWN
}

func (x *GetProviderResponse_Provider_Business) GetResources() []*DeployResource {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *GetProviderResponse_Provider_Business) GetResourceStatus() DeploymentResourceStatus {
	if x != nil {
		return x.ResourceStatus
	}
	return DeploymentResourceStatus_DEPLOYMENT_RESOURCE_STATUS_UNKNOWN
}

type RegisterResponse_SystemInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Os            string                 `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`             // 操作系统
	Arch          string                 `protobuf:"bytes,2,opt,name=arch,proto3" json:"arch,omitempty"`         // 架构
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"` // 主机名
	Ip            string                 `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`             // IP地址
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse_SystemInfo) Reset() {
	*x = RegisterResponse_SystemInfo{}
	mi := &file_deployPB_deploy_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse_SystemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse_SystemInfo) ProtoMessage() {}

func (x *RegisterResponse_SystemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_deployPB_deploy_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse_SystemInfo.ProtoReflect.Descriptor instead.
func (*RegisterResponse_SystemInfo) Descriptor() ([]byte, []int) {
	return file_deployPB_deploy_proto_rawDescGZIP(), []int{11, 0}
}

func (x *RegisterResponse_SystemInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *RegisterResponse_SystemInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *RegisterResponse_SystemInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterResponse_SystemInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

var File_deployPB_deploy_proto protoreflect.FileDescriptor

const file_deployPB_deploy_proto_rawDesc = "" +
	"\n" +
	"\x15deployPB/deploy.proto\x12\bdeployPB\"\x90\x04\n" +
	"\rNotifyRequest\x12\x1c\n" +
	"\taccessKey\x18\x01 \x01(\tR\taccessKey\x12\x1a\n" +
	"\bclientId\x18\x02 \x01(\tR\bclientId\x12\x1c\n" +
	"\trequestId\x18\x03 \x01(\tR\trequestId\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12Q\n" +
	"\x13getProviderResponse\x18\n" +
	" \x01(\v2\x1d.deployPB.GetProviderResponseH\x00R\x13getProviderResponse\x12H\n" +
	"\x10registerResponse\x18\v \x01(\v2\x1a.deployPB.RegisterResponseH\x00R\x10registerResponse\x12B\n" +
	"\x0econnectRequest\x18\f \x01(\v2\x18.deployPB.ConnectRequestH\x00R\x0econnectRequest\x12W\n" +
	"\x15executeBusinesRequest\x18\r \x01(\v2\x1f.deployPB.ExecuteBusinesRequestH\x00R\x15executeBusinesRequest\x12K\n" +
	"\x11challengeResponse\x18\x0e \x01(\v2\x1b.deployPB.ChallengeResponseH\x00R\x11challengeResponseB\x06\n" +
	"\x04data\"\xca\x04\n" +
	"\x0eNotifyResponse\x12\"\n" +
	"\x04type\x18\x01 \x01(\x0e2\x0e.deployPB.TypeR\x04type\x12\x1a\n" +
	"\bclientId\x18\x02 \x01(\tR\bclientId\x12\x1c\n" +
	"\trequestId\x18\x03 \x01(\tR\trequestId\x12Q\n" +
	"\x13getProviderResponse\x18\x05 \x01(\v2\x1d.deployPB.GetProviderResponseH\x00R\x13getProviderResponse\x12E\n" +
	"\x0fregisterRequest\x18\x06 \x01(\v2\x19.deployPB.RegisterRequestH\x00R\x0fregisterRequest\x12B\n" +
	"\x0econnectRequest\x18\a \x01(\v2\x18.deployPB.ConnectRequestH\x00R\x0econnectRequest\x12Z\n" +
	"\x16executeBusinesResponse\x18\b \x01(\v2 .deployPB.ExecuteBusinesResponseH\x00R\x16executeBusinesResponse\x12H\n" +
	"\x10challengeRequest\x18\t \x01(\v2\x1a.deployPB.ChallengeRequestH\x00R\x10challengeRequest\x12N\n" +
	"\x12getProviderRequest\x18\n" +
	" \x01(\v2\x1c.deployPB.GetProviderRequestH\x00R\x12getProviderRequestB\x06\n" +
	"\x04data\"\xc4\x01\n" +
	"\x0eConnectRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12N\n" +
	"\x14execute_busines_type\x18\x03 \x01(\x0e2\x1c.deployPB.ExecuteBusinesTypeR\x12executeBusinesType\x12\x1d\n" +
	"\n" +
	"target_ref\x18\x05 \x01(\tR\ttargetRefJ\x04\b\x04\x10\x05R\amessage\"\x13\n" +
	"\x11CertUpdateRequest\">\n" +
	"\x12CertUpdateResponse\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"\xae\x02\n" +
	"\x10ChallengeRequest\x12 \n" +
	"\voperationId\x18\x01 \x01(\x03R\voperationId\x12\x16\n" +
	"\x06certId\x18\x02 \x01(\x05R\x06certId\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\x12\x18\n" +
	"\akeyAuth\x18\x05 \x01(\tR\akeyAuth\x129\n" +
	"\x06action\x18\x06 \x01(\x0e2!.deployPB.ChallengeRequest.ActionR\x06action\"]\n" +
	"\x06Action\x12\x1c\n" +
	"\x18CHALLENGE_ACTION_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14CHALLENGE_ACTION_SET\x10\x01\x12\x1b\n" +
	"\x17CHALLENGE_ACTION_DELETE\x10\x02\"\xd9\x02\n" +
	"\x11ChallengeResponse\x12 \n" +
	"\voperationId\x18\x01 \x01(\x03R\voperationId\x12\x16\n" +
	"\x06certId\x18\x02 \x01(\x05R\x06certId\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\x12:\n" +
	"\x06result\x18\x05 \x01(\x0e2\".deployPB.ChallengeResponse.ResultR\x06result\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\"\x85\x01\n" +
	"\x06Result\x12\x1c\n" +
	"\x18CHALLENGE_RESULT_UNKNOWN\x10\x00\x12\x1c\n" +
	"\x18CHALLENGE_RESULT_SUCCESS\x10\x01\x12\x1b\n" +
	"\x17CHALLENGE_RESULT_FAILED\x10\x02\x12\"\n" +
	"\x1eCHALLENGE_RESULT_NOT_SUPPORTED\x10\x03\"\xad\x01\n" +
	"\x12GetProviderRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12N\n" +
	"\x14execute_busines_type\x18\x02 \x01(\x0e2\x1c.deployPB.ExecuteBusinesTypeR\x12executeBusinesType\x12+\n" +
	"\x11include_resources\x18\x03 \x01(\bR\x10includeResources\"\xbb\x02\n" +
	"\x0eDeployResource\x12\x1d\n" +
	"\n" +
	"target_ref\x18\x01 \x01(\tR\ttargetRef\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12\x18\n" +
	"\adomains\x18\x04 \x03(\tR\adomains\x12\x1a\n" +
	"\bprotocol\x18\x05 \x01(\tR\bprotocol\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x14\n" +
	"\x05group\x18\a \x01(\tR\x05group\x12\x16\n" +
	"\x06region\x18\b \x01(\tR\x06region\x12\x12\n" +
	"\x04port\x18\t \x01(\rR\x04port\x12L\n" +
	"\favailability\x18\n" +
	" \x01(\x0e2(.deployPB.DeploymentResourceAvailabilityR\favailability\"\xc7\x03\n" +
	"\x13GetProviderResponse\x12D\n" +
	"\tproviders\x18\x01 \x03(\v2&.deployPB.GetProviderResponse.ProviderR\tproviders\x1a\xe9\x02\n" +
	"\bProvider\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06remark\x18\x02 \x01(\tR\x06remark\x12O\n" +
	"\n" +
	"businesses\x18\x03 \x03(\v2/.deployPB.GetProviderResponse.Provider.BusinessR\n" +
	"businesses\x1a\xdf\x01\n" +
	"\bBusiness\x12N\n" +
	"\x14execute_busines_type\x18\x01 \x01(\x0e2\x1c.deployPB.ExecuteBusinesTypeR\x12executeBusinesType\x126\n" +
	"\tresources\x18\x02 \x03(\v2\x18.deployPB.DeployResourceR\tresources\x12K\n" +
	"\x0fresource_status\x18\x03 \x01(\x0e2\".deployPB.DeploymentResourceStatusR\x0eresourceStatus\"\x11\n" +
	"\x0fRegisterRequest\"\xb7\x01\n" +
	"\x10RegisterResponse\x12E\n" +
	"\n" +
	"systemInfo\x18\x01 \x01(\v2%.deployPB.RegisterResponse.SystemInfoR\n" +
	"systemInfo\x1a\\\n" +
	"\n" +
	"SystemInfo\x12\x0e\n" +
	"\x02os\x18\x01 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x02 \x01(\tR\x04arch\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02ip\x18\x04 \x01(\tR\x02ip\"\xee\x02\n" +
	"\x15ExecuteBusinesRequest\x12S\n" +
	"\rrequestResult\x18\x01 \x01(\x0e2-.deployPB.ExecuteBusinesRequest.RequestResultR\rrequestResult\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\tretryable\x18\x03 \x01(\bH\x00R\tretryable\x88\x01\x01\x12.\n" +
	"\x13provider_request_id\x18\x04 \x01(\tR\x11providerRequestId\"\x84\x01\n" +
	"\rRequestResult\x12\x1a\n" +
	"\x16REQUEST_RESULT_UNKNOWN\x10\x00\x12\x1a\n" +
	"\x16REQUEST_RESULT_SUCCESS\x10\x01\x12\x19\n" +
	"\x15REQUEST_RESULT_FAILED\x10\x02\x12 \n" +
	"\x1cREQUEST_RESULT_NOT_SUPPORTED\x10\x03B\f\n" +
	"\n" +
	"_retryable\"\xc7\x02\n" +
	"\x16ExecuteBusinesResponse\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12L\n" +
	"\x12executeBusinesType\x18\x02 \x01(\x0e2\x1c.deployPB.ExecuteBusinesTypeR\x12executeBusinesType\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x12\n" +
	"\x04cert\x18\x05 \x01(\tR\x04cert\x12\x10\n" +
	"\x03key\x18\x06 \x01(\tR\x03key\x12&\n" +
	"\x0echallengeToken\x18\a \x01(\tR\x0echallengeToken\x12,\n" +
	"\x11challengeResponse\x18\b \x01(\tR\x11challengeResponse\x12\x1d\n" +
	"\n" +
	"target_ref\x18\t \x01(\tR\ttargetRef*x\n" +
	"\x04Type\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aCONNECT\x10\x01\x12\x12\n" +
	"\x0eUPDATE_VERSION\x10\x02\x12\x10\n" +
	"\fGET_PROVIDER\x10\x03\x12\f\n" +
	"\bREGISTER\x10\x04\x12\x13\n" +
	"\x0fEXECUTE_BUSINES\x10\x05\x12\r\n" +
	"\tCHALLENGE\x10\x06*\xf0\x05\n" +
	"\x12ExecuteBusinesType\x12\x1b\n" +
	"\x17EXECUTE_BUSINES_UNKNOWN\x10\x00\x12\"\n" +
	"\x1eEXECUTE_BUSINES_ANSSL_CLI_CERT\x10\x01\x12\x1f\n" +
	"\x1bEXECUTE_BUSINES_UPLOAD_CERT\x10\x02\x12\x17\n" +
	"\x13EXECUTE_BUSINES_CDN\x10\x03\x12\x18\n" +
	"\x14EXECUTE_BUSINES_DCDN\x10\x04\x12)\n" +
	"%EXECUTE_BUSINES_ANSSL_CLI_APACHE_CERT\x10\x06\x12)\n" +
	"%EXECUTE_BUSINES_ANSSL_CLI_RUSTFS_CERT\x10\a\x12)\n" +
	"%EXECUTE_BUSINES_ANSSL_CLI_FEINIU_CERT\x10\b\x12)\n" +
	"%EXECUTE_BUSINES_ANSSL_CLI_1PANEL_CERT\x10\t\x12-\n" +
	")EXECUTE_BUSINES_ANSSL_CLI_OPENVPN_AS_CERT\x10\n" +
	"\x12.\n" +
	"*EXECUTE_BUSINES_ANSSL_CLI_UPLOAD_ONLY_CERT\x10\v\x12\x17\n" +
	"\x13EXECUTE_BUSINES_ESA\x10\f\x12\x1b\n" +
	"\x17EXECUTE_BUSINES_EDGEONE\x10\r\x12\x17\n" +
	"\x13EXECUTE_BUSINES_COS\x10\x0e\x12%\n" +
	"!EXECUTE_BUSINES_OSS_CUSTOM_DOMAIN\x10\x0f\x12\x17\n" +
	"\x13EXECUTE_BUSINES_CLB\x10\x10\x12\x17\n" +
	"\x13EXECUTE_BUSINES_ALB\x10\x11\x12\x17\n" +
	"\x13EXECUTE_BUSINES_NLB\x10\x12\x12+\n" +
	"'EXECUTE_BUSINES_ANSSL_CLI_SAFELINE_CERT\x10\x13\x121\n" +
	"-EXECUTE_BUSINES_ANSSL_CLI_1PANEL_WEBSITE_CERT\x10\x14\"\x04\b\x05\x10\x05*\x13EXECUTE_BUSINES_OSS*\xc3\x02\n" +
	"\x18DeploymentResourceStatus\x12&\n" +
	"\"DEPLOYMENT_RESOURCE_STATUS_UNKNOWN\x10\x00\x12$\n" +
	" DEPLOYMENT_RESOURCE_STATUS_READY\x10\x01\x12$\n" +
	" DEPLOYMENT_RESOURCE_STATUS_EMPTY\x10\x02\x12-\n" +
	")DEPLOYMENT_RESOURCE_STATUS_NOT_CONFIGURED\x10\x03\x12*\n" +
	"&DEPLOYMENT_RESOURCE_STATUS_UNAVAILABLE\x10\x04\x12&\n" +
	"\"DEPLOYMENT_RESOURCE_STATUS_PARTIAL\x10\x05\x120\n" +
	",DEPLOYMENT_RESOURCE_STATUS_PERMISSION_DENIED\x10\x06*\xb6\x02\n" +
	"\x1eDeploymentResourceAvailability\x12,\n" +
	"(DEPLOYMENT_RESOURCE_AVAILABILITY_UNKNOWN\x10\x00\x12*\n" +
	"&DEPLOYMENT_RESOURCE_AVAILABILITY_READY\x10\x01\x12,\n" +
	"(DEPLOYMENT_RESOURCE_AVAILABILITY_STOPPED\x10\x02\x12-\n" +
	")DEPLOYMENT_RESOURCE_AVAILABILITY_DISABLED\x10\x03\x12+\n" +
	"'DEPLOYMENT_RESOURCE_AVAILABILITY_LOCKED\x10\x04\x120\n" +
	",DEPLOYMENT_RESOURCE_AVAILABILITY_UNSUPPORTED\x10\x052P\n" +
	"\rDeployService\x12?\n" +
	"\x06Notify\x12\x17.deployPB.NotifyRequest\x1a\x18.deployPB.NotifyResponse(\x010\x01B\x85\x01\n" +
	"\fcom.deployPBB\vDeployProtoP\x01Z(github.com/https-cert/deploy/pb/deployPB\xa2\x02\x03DXX\xaa\x02\bDeployPB\xca\x02\bDeployPB\xe2\x02\x14DeployPB\\GPBMetadata\xea\x02\bDeployPBb\x06proto3"

var (
	file_deployPB_deploy_proto_rawDescOnce sync.Once
	file_deployPB_deploy_proto_rawDescData []byte
)

func file_deployPB_deploy_proto_rawDescGZIP() []byte {
	file_deployPB_deploy_proto_rawDescOnce.Do(func() {
		file_deployPB_deploy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_deployPB_deploy_proto_rawDesc), len(file_deployPB_deploy_proto_rawDesc)))
	})
	return file_deployPB_deploy_proto_rawDescData
}

var file_deployPB_deploy_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_deployPB_deploy_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_deployPB_deploy_proto_goTypes = []any{
	(Type)(0),                                     // 0: deployPB.Type
	(ExecuteBusinesType)(0),                       // 1: deployPB.ExecuteBusinesType
	(DeploymentResourceStatus)(0),                 // 2: deployPB.DeploymentResourceStatus
	(DeploymentResourceAvailability)(0),           // 3: deployPB.DeploymentResourceAvailability
	(ChallengeRequest_Action)(0),                  // 4: deployPB.ChallengeRequest.Action
	(ChallengeResponse_Result)(0),                 // 5: deployPB.ChallengeResponse.Result
	(ExecuteBusinesRequest_RequestResult)(0),      // 6: deployPB.ExecuteBusinesRequest.RequestResult
	(*NotifyRequest)(nil),                         // 7: deployPB.NotifyRequest
	(*NotifyResponse)(nil),                        // 8: deployPB.NotifyResponse
	(*ConnectRequest)(nil),                        // 9: deployPB.ConnectRequest
	(*CertUpdateRequest)(nil),                     // 10: deployPB.CertUpdateRequest
	(*CertUpdateResponse)(nil),                    // 11: deployPB.CertUpdateResponse
	(*ChallengeRequest)(nil),                      // 12: deployPB.ChallengeRequest
	(*ChallengeResponse)(nil),                     // 13: deployPB.ChallengeResponse
	(*GetProviderRequest)(nil),                    // 14: deployPB.GetProviderRequest
	(*DeployResource)(nil),                        // 15: deployPB.DeployResource
	(*GetProviderResponse)(nil),                   // 16: deployPB.GetProviderResponse
	(*RegisterRequest)(nil),                       // 17: deployPB.RegisterRequest
	(*RegisterResponse)(nil),                      // 18: deployPB.RegisterResponse
	(*ExecuteBusinesRequest)(nil),                 // 19: deployPB.ExecuteBusinesRequest
	(*ExecuteBusinesResponse)(nil),                // 20: deployPB.ExecuteBusinesResponse
	(*GetProviderResponse_Provider)(nil),          // 21: deployPB.GetProviderResponse.Provider
	(*GetProviderResponse_Provider_Business)(nil), // 22: deployPB.GetProviderResponse.Provider.Business
	(*RegisterResponse_SystemInfo)(nil),           // 23: deployPB.RegisterResponse.SystemInfo
}
var file_deployPB_deploy_proto_depIdxs = []int32{
	16, // 0: deployPB.NotifyRequest.getProviderResponse:type_name -> deployPB.GetProviderResponse
	18, // 1: deployPB.NotifyRequest.registerResponse:type_name -> deployPB.RegisterResponse
	9,  // 2: deployPB.NotifyRequest.connectRequest:type_name -> deployPB.ConnectRequest
	19, // 3: deployPB.NotifyRequest.executeBusinesRequest:type_name -> deployPB.ExecuteBusinesRequest
	13, // 4: deployPB.NotifyRequest.challengeResponse:type_name -> deployPB.ChallengeResponse
	0,  // 5: deployPB.NotifyResponse.type:type_name -> deployPB.Type
	16, // 6: deployPB.NotifyResponse.getProviderResponse:type_name -> deployPB.GetProviderResponse
	17, // 7: deployPB.NotifyResponse.registerRequest:type_name -> deployPB.RegisterRequest
	9,  // 8: deployPB.NotifyResponse.connectRequest:type_name -> deployPB.ConnectRequest
	20, // 9: deployPB.NotifyResponse.executeBusinesResponse:type_name -> deployPB.ExecuteBusinesResponse
	12, // 10: deployPB.NotifyResponse.challengeRequest:type_name -> deployPB.ChallengeRequest
	14, // 11: deployPB.NotifyResponse.getProviderRequest:type_name -> deployPB.GetProviderRequest
	1,  // 12: deployPB.ConnectRequest.execute_busines_type:type_name -> deployPB.ExecuteBusinesType
	4,  // 13: deployPB.ChallengeRequest.action:type_name -> deployPB.ChallengeRequest.Action
	5,  // 14: deployPB.ChallengeResponse.result:type_name -> deployPB.ChallengeResponse.Result
	1,  // 15: deployPB.GetProviderRequest.execute_busines_type:type_name -> deployPB.ExecuteBusinesType
	3,  // 16: deployPB.DeployResource.availability:type_name -> deployPB.DeploymentResourceAvailability
	21, // 17: deployPB.GetProviderResponse.providers:type_name -> deployPB.GetProviderResponse.Provider
	23, // 18: deployPB.RegisterResponse.systemInfo:type_name -> deployPB.RegisterResponse.SystemInfo
	6,  // 19: deployPB.ExecuteBusinesRequest.requestResult:type_name -> deployPB.ExecuteBusinesRequest.RequestResult
	1,  // 20: deployPB.ExecuteBusinesResponse.executeBusinesType:type_name -> deployPB.ExecuteBusinesType
	22, // 21: deployPB.GetProviderResponse.Provider.businesses:type_name -> deployPB.GetProviderResponse.Provider.Business
	1,  // 22: deployPB.GetProviderResponse.Provider.Business.execute_busines_type:type_name -> deployPB.ExecuteBusinesType
	15, // 23: deployPB.GetProviderResponse.Provider.Business.resources:type_name -> deployPB.DeployResource
	2,  // 24: deployPB.GetProviderResponse.Provider.Business.resource_status:type_name -> deployPB.DeploymentResourceStatus
	7,  // 25: deployPB.DeployService.Notify:input_type -> deployPB.NotifyRequest
	8,  // 26: deployPB.DeployService.Notify:output_type -> deployPB.NotifyResponse
	26, // [26:27] is the sub-list for method output_type
	25, // [25:26] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_deployPB_deploy_proto_init() }
func file_deployPB_deploy_proto_init() {
	if File_deployPB_deploy_proto != nil {
		return
	}
	file_deployPB_deploy_proto_msgTypes[0].OneofWrappers = []any{
		(*NotifyRequest_GetProviderResponse)(nil),
		(*NotifyRequest_RegisterResponse)(nil),
		(*NotifyRequest_ConnectRequest)(nil),
		(*NotifyRequest_ExecuteBusinesRequest)(nil),
		(*NotifyRequest_ChallengeResponse)(nil),
	}
	file_deployPB_deploy_proto_msgTypes[1].OneofWrappers = []any{
		(*NotifyResponse_GetProviderResponse)(nil),
		(*NotifyResponse_RegisterRequest)(nil),
		(*NotifyResponse_ConnectRequest)(nil),
		(*NotifyResponse_ExecuteBusinesResponse)(nil),
		(*NotifyResponse_ChallengeRequest)(nil),
		(*NotifyResponse_GetProviderRequest)(nil),
	}
	file_deployPB_deploy_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_deployPB_deploy_proto_rawDesc), len(file_deployPB_deploy_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_deployPB_deploy_proto_goTypes,
		DependencyIndexes: file_deployPB_deploy_proto_depIdxs,
		EnumInfos:         file_deployPB_deploy_proto_enumTypes,
		MessageInfos:      file_deployPB_deploy_proto_msgTypes,
	}.Build()
	File_deployPB_deploy_proto = out.File
	file_deployPB_deploy_proto_goTypes = nil
	file_deployPB_deploy_proto_depIdxs = nil
}
